app:
  image: izupet/app
  container_name: {{project_name}}_app_1
  volumes:
    - ./app/www.conf:/etc/php5/fpm/pool.d/www.conf
    - ./../../../{{project_name}}:/opt/web
  ports:
    - "9000"
    - "8080:8080"
  links:
    - memcached
    - db
memcached:
  image: izupet/memcached
  container_name: {{project_name}}_memcached_1
  ports:
   - "11211"
nginx:
  image: izupet/nginx
  container_name: {{project_name}}_nginx_1
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/default.conf:/etc/nginx/sites-available/default.conf
  volumes_from:
    - app
  links:
    - app
  ports:
    - "80:80"
db:
  image: izupet/db
  container_name: {{project_name}}_db_1
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: {{mysql_database}}
    MYSQL_USER: {{mysql_user}}
    MYSQL_PASSWORD: {{mysql_password}}
    MYSQL_ROOT_PASSWORD: {{mysql_root_password}}
